# Generated by Django 3.1.7 on 2021-03-26 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authtoken.token')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SymbolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fermatapi.category')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fermatapi.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='EquationText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=65535)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('size', models.FloatField()),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fermatapi.equation')),
            ],
        ),
        migrations.CreateModel(
            name='EquationSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('size', models.FloatField()),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fermatapi.equation')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fermatapi.symbol')),
            ],
        ),
    ]
