# Generated by Django 3.1.7 on 2021-03-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fermatapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
