# Generated by Django 3.1.7 on 2021-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermatapi', '0002_auto_20210309_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='image_url',
        ),
        migrations.AddField(
            model_name='symbol',
            name='entity_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
